apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iixo5f5dq-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iixo5f5dq-java-springboot-gitops